"""Discovery schemas (roadmap Phase 16).

Tasks describe what to run; Candidates are the normalized, deduplicated
output the Discovery Engine produces for the research agent.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urlparse

from app.discovery.context.models import SearchContext


def _now() -> datetime:
    return datetime.now(timezone.utc)


@dataclass
class DiscoveryTask:
    """One provider invocation generated by the Discovery Engine."""

    provider_name: str
    kind: str  # "image" | "web"
    query: str | None = None
    image: Path | None = None
    context: SearchContext | None = None


@dataclass
class Candidate:
    """A normalized public candidate page found by a provider."""

    url: str
    source: str = "unknown"
    title: str = ""
    domain: str = ""
    kind: str = "web"
    reason: str = ""
    discovered_at: datetime = field(default_factory=_now)
    images: list[str] = field(default_factory=list)
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not self.domain:
            self.domain = derive_domain(self.url)


def derive_domain(url: str) -> str:
    try:
        clean = url.strip()
        parts = urlparse(clean)
        if not parts.netloc and "://" not in clean:
            parts = urlparse(f"//{clean}")
        return parts.netloc.lower()
    except ValueError:
        return ""


def canonical_url(url: str) -> str:
    """Lowercase scheme+host key (query preserved) used to deduplicate."""
    try:
        parts = urlparse(url.strip())
        key = f"{parts.scheme.lower()}://{parts.netloc.lower()}{parts.path}"
        if parts.query:
            key += f"?{parts.query}"
        return key
    except ValueError:
        return url.strip().lower()